[build]
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"
  publish = "dist"

# === Canonical Domain Redirects ===
# These rules are more specific and run first.
# They force all traffic to the single, canonical domain (https://startsnap.fun).

[[redirects]]
  from = "https://www.startsnap.fun/*"
  to = "https://startsnap.fun/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://startsnap.xyz/*"
  to = "https://startsnap.fun/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.startsnap.xyz/*"
  to = "https://startsnap.fun/:splat"
  status = 301
  force = true

# === Single Page App (SPA) Fallback ===
# This is the essential rule for React Router.
# It MUST come last as it's the catch-all.

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200